project:
  type: website
  output-dir: docs

website:
  title: "Angel Merino | Data Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre MÃ­

format:
  html:
    theme: flatly # Un tema limpio y profesional para el portafolio principal
    css: styles.css
    toc: false

lang: es