project:
  type: website
  output-dir: ../docs

website:
  title: "Angel Merino | Projects Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre MÃ­
      - href: proyectos.qmd
        text: Proyectos

format:
  html:
    theme: flatly 
    css: styles.css
    toc: false

lang: es