project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - about.qmd
    - proyectos.qmd
    - publicaciones.qmd

website:
  title: "Angel Merino | Portafolio de Proyectos"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre MÃ­
      - href: proyectos.qmd
        text: Proyectos
      - href: publicaciones.qmd   
        text: Publicaciones
format:
  html:
    theme: 
      - flatly 
      - scustom.scss
    css: styles.css
    toc: false

lang: es