project:
  type: website
  output-dir: ../docs

website:
  title: "Angel Merino | Projects Portfolio"
  navbar:
    left:
      - href: 0_index.qmd
        text: Inicio
      - href: 1_about.qmd
        text: Sobre MÃ­
      - href: 2_proyectos.qmd
        text: Proyectos
      - href: 3_publicaciones.qmd   
        text: Publicaciones
format:
  html:
    theme: 
      - flatly 
      - custom.scss
    css: styles.css
    toc: false

lang: es