project:
  type: website
  output-dir: ../docs

website:
  title: "Angel Merino | Data Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: about.qmd
        text: Sobre MÃ­
    right:
      - text: "Proyectos"
        menu:
          - text: "Help Desk CENACE"
            href: 1_cenace_helpdesk/index.html
          - text: "Recomendador CT"
            href: 2_ct_chatbot/index.html
          - text: "Chatbot Salsas Castillo"
            href: 3_salsas_chatbot/index.html

format:
  html:
    theme: flatly # Un tema limpio y profesional para el portafolio principal
    css: styles.css
    toc: false

lang: es